import Head from "next/head";

const Header = () => {
  return (
    <Head>
      <title>Analyze</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="images/logo.svg" />
    </Head>
  );
};

export default Header;
